title: CITI Data Science
description: Data Science Page
author: Cyberinfrastructure and Technology Integration
logo:  https://github.com/clemsonciti/lesson-template/raw/gh-pages/img/paw.gif
github: https://github.com/clemsonciti
about:
disqus_shortname: citids
google_analytics: UA-72862926-1
urls:
    - text: Home
      url: /data-science/
      icon: fa-home
      layout: post
    - text: About
      url: /data-science/about/
      icon: fa-comments
    - text: Projects
      url: /data-science/projects/
      icon: fa-desktop
    - text: Resume
      url: '/data-science/#'
      icon: fa-graduation-cap
    - text: Github
      url: https://github.com/clemsonciti
      icon: fa-github

share:
  twitter_username: \#
  fb_appid: 000000000000


enableTags: true
tagarray: []

url: "https://clemsonciti.github.io/data-science"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist
